# Generated by Django 5.0.6 on 2024-06-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=12, verbose_name='NIT.')),
                ('nombreEdificio', models.CharField(max_length=80, verbose_name='Nombre Edificio')),
                ('dirEdificio', models.CharField(max_length=100, verbose_name='Dirección Edificio')),
                ('telAdmon', models.IntegerField(max_length=10, verbose_name='Teléfono Admón')),
                ('correoAdmon', models.CharField(max_length=100, verbose_name='Correo Admón')),
            ],
        ),
    ]
