# Generated by Django 5.0.4 on 2024-06-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsproapp', '0006_producto_alter_cliente_teladmon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='modelo',
            new_name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='fotoProd',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Foto Producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='modeloProd',
            field=models.CharField(default='Default_Modelo', max_length=50, verbose_name='Modelo del Producto'),
        ),
    ]
