# Generated by Django 5.0.6 on 2024-06-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsproapp', '0010_rename_id_producto_idprod'),
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('idEdif', models.AutoField(primary_key=True, serialize=False)),
                ('nitEdif', models.CharField(max_length=12, verbose_name='NIT.')),
                ('nombreEdif', models.CharField(max_length=30, unique=True)),
                ('direccionEdif', models.CharField(max_length=50)),
                ('nombreProp', models.CharField(max_length=50)),
                ('emailAdmon', models.EmailField(max_length=254, unique=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('es_personal', models.BooleanField(default=False)),
                ('roles', models.CharField(choices=[('usuario', 'Propietario'), ('admin', 'Administrador')], default='usuario', max_length=7)),
            ],
        ),
    ]
