# Generated by Django 5.0.6 on 2024-06-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsproapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='telAdmon',
            field=models.IntegerField(verbose_name='Teléfono Admón'),
        ),
    ]
