# Generated by Django 5.0.6 on 2024-06-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsproapp', '0002_alter_usuarios_teladmon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='telAdmon',
            field=models.IntegerField(max_length=10, verbose_name='Teléfono Admón'),
        ),
    ]
