# Generated by Django 5.0.4 on 2024-06-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsproapp', '0005_rename_usuarios_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('modelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProd', models.CharField(max_length=20, verbose_name='Descripcion del Producto')),
                ('marcaProd', models.CharField(max_length=80, verbose_name='Marca Camara')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telAdmon',
            field=models.CharField(max_length=10, verbose_name='Teléfono Admón'),
        ),
    ]
