# Generated by Django 5.0.4 on 2024-06-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsproapp', '0008_alter_producto_modeloprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='modeloProd',
            field=models.CharField(default='', max_length=50, verbose_name='Modelo del Producto'),
        ),
    ]
