# Generated by Django 5.0.6 on 2024-06-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsproapp', '0009_alter_producto_modeloprod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id',
            new_name='idProd',
        ),
    ]
